### ISSUE TITLE
Reenable codeQL workflow

### ISSUE THREAD

**Issue by kevalpatel2106** [kevalpatel2106/pocket-ci#167]
**Context**

There was a bug in CodeQL kotlin analysis (https://github.com/github/codeql-action/issues/1417), that keeps failing the CodeQL build with the following exception:

[Sample Action:](https://github.com/kevalpatel2106/pocket-ci/actions/runs/4258944596/jobs/7410687910)

```
[2023-02-24 03:06:05] [autobuild] org.gradle.execution.TaskSelectionException: Task 'testClasses' not found in root project 'Pocket CI' and its subprojects.
[249](https://github.com/kevalpatel2106/pocket-ci/actions/runs/4258944596/jobs/7410687910#step:5:250)
  [2023-02-24 03:06:05] [autobuild] 	at org.gradle.execution.DefaultTaskSelector.getSelection(DefaultTaskSelector.java:86)
[250](https://github.com/kevalpatel2106/pocket-ci/actions/runs/4258944596/jobs/7410687910#step:5:251)
  [2023-02-24 03:06:05] [autobuild] 	at org.gradle.execution.selection.DefaultBuildTaskSelector.resolveTaskName(DefaultBuildTaskSelector.java:97)
[251](https://github.com/kevalpatel2106/pocket-ci/actions/runs/4258944596/jobs/7410687910#step:5:252)
  [2023-02-24 03:06:05] [autobuild] 	at org.gradle.execution.commandline.CommandLineTaskParser.parseTasks(CommandLineTaskParser.java:49)
[252](https://github.com/kevalpatel2106/pocket-ci/actions/runs/4258944596/jobs/7410687910#step:5:253)
  [2023-02-24 03:06:05] [autobuild] 	at org.gradle.execution.TaskNameResolvingBuildTaskScheduler.scheduleRequestedTasks(TaskNameResolvingBuildTaskScheduler.java:50)
[253](https://github.com/kevalpatel2106/pocket-ci/actions/runs/4258944596/jobs/7410687910#step:5:254)
  [2023-02-24 03:06:05] [autobuild] 	at org.gradle.execution.DefaultTasksBuildTaskScheduler.scheduleRequestedTasks(DefaultTasksBuildTaskScheduler.java:72)
[254](https://github.com/kevalpatel2106/pocket-ci/actions/runs/4258944596/jobs/7410687910#step:5:255)
  [2023-02-24 03:06:05] [autobuild] 	at org.gradle.initialization.DefaultTaskExecutionPreparer.lambda$scheduleRequestedTasks$0(DefaultTaskExecutionPreparer.java:46)
[255](https://github.com/kevalpatel2106/pocket-ci/actions/runs/4258944596/jobs/7410687910#step:5:256)
  [2023-02-24 03:06:05] [autobuild] 	at org.gradle.internal.Factories$1.create(Factories.java:31)
```

As the timeline pointed out [here](https://github.com/github/codeql-action/issues/1417#issuecomment-1400208644) the fix has been merged and we need to wait couple of weeks for the new release. As of 25th Feb fix is not yet available it looks like as the builds are still failing.

As a fix I disabled CodeQL until I get some answers

**Comment by kevalpatel2106** [comment]
As mentioned in https://github.com/github/codeql-action/issues/1417#issuecomment-1446028805, the issue seems to be the auto-build breaking because of the version catalogue changes.  


Autobuild is unable to identify this as an Android project, because it cannot find AGP dependency in build.gradle (as it's something like libs.XXX.XXXX after migrating to the version catalog) and run the appropriate task (assemble). Instead, it identifies it as a java project and uses `testClasses` task.
